### ISSUE TITLE
Improve linter styling

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-SpreadsheetsHelper#4]
File to be updated: [dialog.html](https://github.com/one-zero-eight/InNoHassle-SpreadsheetsHelper/blob/main/src/dialog.html)

- [x] check paddings, margins and so on.
- [x] change main color to #9747ff
- [x] replace "Open Settings" link with corresponding button one-zero-eight/InNoHassle-SpreadsheetsHelper#1 
- [x] suggest new ideas and create tasks for those

Current (sidebar view): 

![Image](https://github.com/one-zero-eight/InNoHassle-SpreadsheetsHelper/assets/69670642/f5d1321b-15fb-41eb-8c63-d213720b2d3b)

Warnings
![Image](https://github.com/one-zero-eight/InNoHassle-SpreadsheetsHelper/assets/69670642/bdbc2951-40aa-49ae-9dfe-a771efe2b65b)

**Comment by versceana** [comment]
1) check references :) 
2) change background on white
